# Generated by Django 2.1.4 on 2018-12-21 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implemented', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
                ('location', models.CharField(default='', max_length=128)),
                ('type', models.IntegerField(default=0)),
                ('units', models.CharField(blank=True, default='', max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.Sensors')),
            ],
        ),
    ]
