# Generated by Django 2.1.4 on 2018-12-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensors',
            name='implemented',
        ),
    ]
