# Generated by Django 2.2.10 on 2020-03-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_remove_sensors_implemented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorsdata',
            name='value',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
    ]
