# Generated by Django 2.2.10 on 2020-03-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_auto_20200323_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='display_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
