# Generated by Django 2.2.10 on 2020-03-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_sensors_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='display_max',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='sensors',
            name='display_min',
            field=models.FloatField(default=0.0),
        ),
    ]
