# Generated by Django 2.2.13 on 2021-03-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_auto_20200324_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
