# Generated by Django 2.2.13 on 2022-03-19 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('location', models.CharField(default='', max_length=128)),
                ('type', models.IntegerField(default=0)),
                ('units', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('display_name', models.CharField(default='', max_length=128)),
                ('display_min', models.FloatField(default=0.0)),
                ('display_max', models.FloatField(default=100.0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('time', models.DateTimeField(blank=False)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.Sensor')),
            ],
        ),
    ]
